### ISSUE TITLE
Division by Zero error on live run

### ISSUE THREAD

**Issue by seannowotny** [brookmiles/freqtrade-stuff#3]
On a Obelisk_Ichimoku_Slow_v1_3 live run with a small amount I got this error after a few days.
Just leaving this here so people can see.

2021-05-12 09:00:14,565 - freqtrade.persistence.models - INFO - MARKET_BUY has been fulfilled for Trade(id=7, pair=SUSHI/USD, amount=0.00000000, open_rate=17.70890000, open_since=2021-05-12 09:00:12).
2021-05-12 09:00:16,038 - freqtrade.commands.trade_commands - ERROR - float division by zero
2021-05-12 09:00:16,039 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 184, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 698, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/freqtrade/freqtrade/freqtradebot.py", line 810, in handle_trade
    if self._check_and_execute_sell(trade, sell_rate, buy, sell):
  File "/freqtrade/freqtrade/freqtradebot.py", line 945, in _check_and_execute_sell
    should_sell = self.strategy.should_sell(
  File "/freqtrade/freqtrade/strategy/interface.py", line 516, in should_sell
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/freqtrade/freqtrade/persistence/models.py", line 554, in calc_profit_ratio
    profit_ratio = (close_trade_value / self.open_trade_value) - 1
ZeroDivisionError: float division by zero
2021-05-12 09:00:16,040 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-05-12 09:00:16,041 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-05-12 09:00:16,108 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-05-12 09:00:16,112 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trades manually on FTX, or '/start' the bot again and use '/stopbuy' to handle ope
n trades gracefully. \n"}
2021-05-12 09:00:16,168 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-05-12 09:00:16,168 - apscheduler.scheduler - INFO - Scheduler has been shut down

**Comment by brookmiles** [comment]
I don't believe this is related to any specific strategy of mine? You may want to post this on https://github.com/freqtrade/freqtrade
